id = "modern-react-snippets-zed"
name = "Modern React Snippets Zed"
version = "1.0.0"
schema_version = 1
authors = ["KAGU <https://github.com/kagulion>"]
description = "Modern React, Redux, React Native, Hooks, and TypeScript snippets for Zed editor."
repository = "https://github.com/kagulion/modern-react-snippets-zed-plugin"

snippets = [
  "./snippets/javascript.json",
  "./snippets/typescript.json",
  "./snippets/tsx.json"
]
