id = "modern-react-snippets"
name = "Modern React Snippets"
version = "1.0.0"
schema_version = 1
authors = ["KAGU"]
description = "Modern React, Redux, React Native, Hooks, and TypeScript snippets."
repository = "https://github.com/kagulion/modern-react-snippets-zed-plugin"

snippets = [
  "./snippets/javascript.json",
  "./snippets/typescript.json",
  "./snippets/tsx.json"
]
